name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nicknielsen/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nicknielsen/react-test-up npm test

      -
        name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: nicknielsen/multi-client-up

      -
        name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: nicknielsen/multi-nginx-up

      -
        name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: nicknielsen/multi-server-up

      -
        name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: nicknielsen/multi-worker-up

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-docker
      #     environment_name: Multi-docker-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
